function renderpage() {
    const title = document.title;
    const body = document.body;
    const header = document.createElement('header');
    const div = document.createElement('div');
    div.className = 'nav-logo';
    div.textContent = "温州县域公交";
    const nav = document.createElement('nav');
    const index = document.createElement('a');
    index.href = "../../index.html";
    index.textContent = "首页";
    const rtbus = document.createElement('a');
    rtbus.href = "https://www.mygolbs.com/home";
    rtbus.textContent = "实时公交";
    const about = document.createElement('a');
    about.href = "../../pages/about.html";
    about.textContent = "关于我们";
    const tips = document.createElement('a');
    tips.href = "../../pages/tips.html";
    tips.textContent = "乘车指南";
    index.className = rtbus.className = about.className = tips.className = "nav-link";
    nav.append(index, rtbus, about, tips);
    header.append(div, nav);
    const h1 = document.createElement('h1');
    h1.textContent = title;
    const searchContainer = document.createElement('div');
    searchContainer.className = 'search-container';
    const searchInput = document.createElement('input');
    searchInput.type = 'text';
    searchInput.id = 'search-input';
    searchInput.placeholder = '输入公交线路';
    searchInput.className = 'search-input';
    const searchBtn = document.createElement('button');
    searchBtn.id = 'search-btn';
    searchBtn.className = 'btn';
    searchBtn.textContent = '搜索';
    // searchBtn.onclick = searchRoute();
    const searchResult = document.createElement('div');
    searchResult.id = 'search-result';
    searchResult.className = 'search-result';
    searchContainer.append(searchInput, searchBtn, searchResult);
    const busList = document.createElement('ul');
    busList.className = 'bus-list';
    const footer = document.createElement('footer');
    const p1 = document.createElement('p');
    p1.textContent = '温州县域公交信息平台 © 2026 版权所有';
    const p2 = document.createElement('p');
    p2.textContent = '温馨提示：本平台为公益性信息平台，无任何商业运营行为';
    const p3 = document.createElement('p');
    p3.textContent = '数据更新时间：2026年8月';
    footer.append(p1, p2, p3);
    body.append(header, h1, searchContainer, busList, footer);
    console.log("页面已渲染");
}